version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build test and push:
    executor:
      name: node/default
    steps:
      - checkout
      
#      - node/install-npm:
#          version: 6.14.9
#          
#      - node/install:
#          node-version: 14.15.3
#          install-npm: false
#          
#      - run:
#          command: npm install
#          
#      - run:
#          command: npm run test
#          
#      - run:
#          command: npm run build

      - run:
          git checkout -b heroku-deploy

      - run:
          mkdir out
          touch out/test
          
      - run:
          git add -f ./out/test

      - run:
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "circle ci"
            git commit -m "commit by CircleCI"

      - run:
          git push -f origin heroku-deploy:heroku-deploy

workflows:
  deployment:
    jobs:
      - build test and push