version: 2.1

orbs:
  node: circleci/node@4.1.0
#  slack: circleci/slack@3.4.2

jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14
      - run: npm run format
      - run: npm run test
#      # Send status to slack.
#      - slack/status:
#          success_message: "Test is OK.🤗"
#          failure_message: "Test Failed.🥺"
#          webhook: $SLACK_WEBHOOK

workflows:
  test:
    jobs:
      - test
