version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
#  test:
#    executor:
#      name: node/default
#    steps:
#      - checkout
#      - node/install-npm:
#          version: 6.14.9
#      - node/install:
#          node-version: 14.15.3
#          install-npm: false
#      - run:
#          command: npm install
#      - run:
#          command: npm run test
#      - run:
#          command: npm run build
  push:
    docker:
      - image: 'cimg/base:stable'    
    steps:
      - run:
          command: echo $CIRCLE_BRANCH
      - run:
          command: echo $CIRCLE_USERNAME
      - run:
          command: echo $CIRCLE_REPOSITORY_URL
      - run:
          mkdir -p ~/.ssh

      - run:
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          echo "test" > ~/.ssh/ci.key

      - run:
          chmod 700 ~/.ssh
      - run:
          chmod 600 ~/.ssh/ci.key
      - run:
          ls -la ~/.ssh

      - run:
          export GIT_SSH_COMMAND='ssh -i ~/.ssh/ci.key'

      - run:
          git clone $CIRCLE_REPOSITORY_URL ./test

workflows:
  deployment:
    jobs:
      - push
#      - test
#      - push:
#          requires: 
#            - test
