version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-npm:
          version: 6.14.9
      - node/install:
          node-version: 14.15.3
      - run:
          command: npm install
      - run:
          command: npm run test
  push:
    docker:
      - image: 'cimg/base:stable'    
    steps:
      - run:
          command: echo hi

workflows:
  deployment:
    jobs:
      - test
      - push:
          requires: 
            - test