name: Deploy

on:
  push:
    branches: [master, refactor]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build
      - name: Use Node.js 14.15.3, Npm 6.14.9
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run format
      - run: npm run test
      - run: npm run build

      - run: git status
      - run: git remote -v
      - run: git checkout -b test-work
      - run: git add -f ./out
      - run: git commit --allow-empty -m "commit by GitHub Actions"

      # # Commit to deploy to heroku.
      # - name: Commit
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     # On way to use heroku-deploy branch.
      #     push: origin ${{ github.ref }}:heroku-deploy --force
      #     # Add force because out is ignored.
      #     add: 'out --force'
