name: Deploy

on:
  push:
    branches: [master, refactor]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build and deploy:
    runs-on: ubuntu-latest

    env:
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      DEPLOY_BRANCH: ${{ secrets.API_ENDPOINT }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build
      - name: Use Node.js 14.15.3, Npm 6.14.9
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.3'

      - run: npm install

      - run: npm run format

      - run: npm run test

      - run: npm run build

      - name: Setup git user email and name
        run : |
          git config --global user.email "githubactions@example.com"
          git config --global user.name "GitHub Actions"

      - run: git checkout -b $DEPLOY_BRANCH

      - name: Add built assest
        run: git add -f ./out

      - run: git commit --allow-empty -m "commit by GitHub Actions"

      - run: git push -f origin $DEPLOY_BRANCH:$DEPLOY_BRANCH
