# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ work ]
  pull_request:
    branches: [ work ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GRPC_ADDR: ${{ secrets.GRPC_ADDR }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.15.3, Npm 6.14.9
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run format
      - run: npm run test
      - run: npm run build
      
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: work-commit
          add: 'out'
