name: Test and Deploy

on:
  push:
    # Targets are all branches.
    # Run deployment if a branch is master.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # There are no inputs.

jobs:
  test_build_and_push:
    runs-on: ubuntu-latest

    env:
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      DEPLOY_BRANCH: ${{ secrets.DEPLOY_BRANCH }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.3, Npm 6.14.9
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.3'

      - run: npm install

      - run: npm run format

      - run: npm run test


      # Run the below actions if the ref is equal to master.

      # Output build assets to ./out
      - run: npm run build
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Setup git user email and name
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.email "githubactions@example.com"
          git config --global user.name "GitHub Actions"

      - run: git checkout -b $DEPLOY_BRANCH
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Add built assest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: git add -f ./out

      - run: git commit --allow-empty -m "commit by GitHub Actions"
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Push to a deployment branch
        if: ${{ github.ref == 'refs/heads/master' }}
        run: git push -f origin $DEPLOY_BRANCH:$DEPLOY_BRANCH
